import Head from "next/head";

export default function Blog() {

    const movies = [
  {
    name: "avengers",
    img: "https://www.bing.com/images/search?view=detailV2&ccid=OPqKjxs7&id=16379030C9E9C379391D524466BC07706E785662&thid=OIP.OPqKjxs7lcWH3TOVTKpwRwHaDt&mediaurl=https%3a%2f%2fstatic1.srcdn.com%2fwordpress%2fwp-content%2fuploads%2f2023%2f11%2foriginal-avengers-team-cast-in-the-mcu.jpg&exph=1000&expw=2000&q=avengers&FORM=IRPRST&ck=35355ACD2F8256CE4F0CA08151C0F0A0&selectedIndex=2&itb=0",
    desc : " Directed by me",
  },
   {
    name: "Iron man",
    img: "https://e0.pxfuel.com/wallpapers/979/623/desktop-wallpaper-iron-man-movies-iron-man-ironman-avengers-marvel.jpg",
    desc : " Directed by you",
  },
   {
    name: "matrixs",
    img: "https://www.bing.com/images/search?view=detailV2&ccid=LRAzi%2b1c&id=FC8CC18066F04E5912B6844EEACCA0BAB19CDD51&thid=OIP.LRAzi-1cTiZUNCARU0UWmAHaFj&mediaurl=https%3a%2f%2fth.bing.com%2fth%2fid%2fR.2d10338bed5c4e265434201153451698%3frik%3dUd2csbqgzOpOhA%26riu%3dhttp%253a%252f%252fwww.scriptgodsmustdie.com%252fwp-content%252fuploads%252f2013%252f02%252fthe-matrix.jpg%26ehk%3dI6%252fTQHb920I2PsEngie%252fn8oKqpB%252fs7QeRE1cWEuS0hE%253d%26risl%3d%26pid%3dImgRaw%26r%3d0&exph=768&expw=1024&q=matrix+&FORM=IRPRST&ck=A75818886086E52CF567F3601130B648&selectedIndex=6&itb=0",
    desc: " Directed by us",
  },
];
  return (
    <>
      <Head>
        <title> BLOG | the movie lover club </title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      <div>
        Blog
      </div>
    </>
  );
}
