import Head from "next/head";
import { useState } from "react";
//MUI Imports
import Box from '@mui/material/Box';
import Button from '@mui/material/Button';
import MyAppBar from "./component/myappbar";
import { ThemeProvider } from "@mui/material";
import { theme, darkTheme } from "@/styles/mui/theme";
 
export default function Home() {
  const [visible, setVisible] = useState(false);
  const movies = [
    {
      name: "Avengers",
      img: "https://disney.images.edge.bamgrid.com/ripcut-delivery/v2/variant/disney/7b350a2f-0b3e-4033-8125-34c4d67e3bbe/compose?aspectRatio=1.78&format=webp&width=1200%22",
      desc: "Directed by Joss Whedon"
    },
    {
      name: "Terminator",
      img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTqsW3jntlwkuRcxsIT1rLpjtC3HuMukv7elQ&s",
      desc: "Directed by james cameron"
    },
    {
      name: "Inceptor",
      img: "https://i.ytimg.com/vi/_Mc0TZueRQE/maxresdefault.jpg",
      desc: "Directed by Chris Nolan"
    },
    {
      name: "Jurassic Park",
      img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTMs7X6ePzaoeG2pl3Q8gXOw6blAFrfh4G-VQ&s",
      desc: "Directed by Steven spieling"
    }
  ];
  return (
    <>
    <ThemeProvider theme={darkTheme}>
      <Head>
        <title>The Movie Lovers Club</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      <MyAppBar />
      <Button onClick={() => setVisible(!visible)}>TOGGLE</Button>
      <Box height="200px">
        {
          visible ? (<Box sx={{background:"grey", width:"500px", height:"300px"}}></Box>):(<></>)
        }
      </Box>
      </ThemeProvider>
    </>
  );
};